FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install dependencies

COPY package.json ./

COPY yarn.lock ./

COPY . .

RUN yarn

RUN yarn build

EXPOSE 8001

CMD ["node","dist/src/server"]