export enum USER_ACCESS {
  ADSL_SERVICES = "سرویس های ADSL",
  TDLTE_SERVICES = "سرویس های TD-LTE",
  OWA_SERVICES = "سرویس های OWA",
  CUSTOMERS = "مشترکین",
  ALL_CUSTOMERS = "مشترکین کل",
  DISCOUNT_PIN = "پین تخفیف",
  INVOICE = "فاکتور",
  CANCELED_INVOICE = "فاکتور برگشتی",
  DONE_INVOICE = "فاکتور بسته شده",
  DOCUMENT_ALL = "کل اسناد",
  DOCUMENT_READ = "مشاهده اسناد",
  STATISTICS = "گزارشات",
  TASKS = "تسک ها",
  PRODUCTS = "خرید و فروش",
  CANCELED_SELL = "برگشتی تهران",
  SMS = "اس ام اس",
  AGENT = "عاملین",
  ALL_AGENT = "عاملین کل",
  LOGS = "لاگ ها",
  AGENT_LOGS = "لاگ های عامل",
  INVOICES_ACCOUNTING = "حسابداری فاکتور ها",
  CLUE = "سرنخ"
}
